file = open('Names.txt', 'w')
file.write('name1\n')
file.write('name2\n')
file.write('name3\n')
file.close()
file = open('Names.txt', 'a')
file.write(input('enter a name to add: '))
file.close()
file = open('Names.txt', 'r')
print(file.read())
